language: r
cache: packages

r:
  - oldrel
  - release
  - devel
  
jdk:
  - oraclejdk6
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk9
  
r_packages:
  - covr
  
r_github_packages:
  - miraisolutions/xlconnectjars
  
script:
  - |
    R CMD build --compact-vignettes=both --md5 .
    export FULL_TEST_SUITE=1
    R CMD check XLConnect*tar.gz
    travis_wait 30 Rscript -e 'covr::codecov()'
