language: r
cache: packages

before_install:
  - sudo add-apt-repository ppa:webupd8team/java -y
  - sudo add-apt-repository ppa:linuxuprising/java -y # java10 & java11
  - sudo apt-get update -q
  
r_packages:
  - covr
  
r_github_packages:
  - miraisolutions/xlconnectjars
  
matrix:
  include:
    - r: release
      addons:
        apt:
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
    - r: release
      addons:
        apt:
          packages:
            - oracle-java11-installer # java9 is not available through webupd8team ppa anymore
            - oracle-java11-set-default
    - r: devel
      addons:
        apt:
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
    - r: devel
      addons:
        apt:
          packages:
            - oracle-java11-installer
            - oracle-java11-set-default
    - r: oldrel
      addons:
        apt:
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
    - r: oldrel
      addons:
        apt:
          packages:
            - oracle-java11-installer
            - oracle-java11-set-default
  
script:
  - |
    java -version
    R CMD build --compact-vignettes=both --md5 .
    export FULL_TEST_SUITE=1
    R CMD check XLConnect*tar.gz
    travis_wait 30 Rscript -e 'covr::codecov()'
