language: r
cache: packages
  
r_packages:
  - covr
  
r_github_packages:
  - miraisolutions/xlconnectjars
  
matrix:
  include:
    - r: release
      addons:
        apt:
          packages:
            - openjdk-6-jdk
    - r: release
      addons:
        apt:
          packages:
            - openjdk-7-jdk
    - r: release
      addons:
        apt:
          packages:
            - openjdk-8-jdk
    - r: release
      addons:
        apt:
          packages:
            - openjdk-9-jdk
    - r: devel
      addons:
        apt:
          packages:
            - openjdk-6-jdk
    - r: devel
      addons:
        apt:
          packages:
            - openjdk-7-jdk
    - r: devel
      addons:
        apt:
          packages:
            - openjdk-8-jdk
    - r: devel
      addons:
        apt:
          packages:
            - openjdk-9-jdk
    - r: oldrel
      addons:
        apt:
          packages:
            - openjdk-8-jdk
  
script:
  - |
    java -version
    R CMD build --compact-vignettes=both --md5 .
    export FULL_TEST_SUITE=1
    R CMD check XLConnect*tar.gz
    travis_wait 30 Rscript -e 'covr::codecov()'
