language: r
cache: packages
  
r_packages:
  - covr
  
r_github_packages:
  - miraisolutions/xlconnectjars
  
matrix:
  include:
    - r: release
      jdk: openjdk6
    - r: release
      jdk: openjdk7
    - r: release
      jdk: openjdk8
    - r: release
      jdk: openjdk9
    - r: release
      jdk: oraclejdk6
    - r: release
      jdk: oraclejdk7
    - r: release
      jdk: oraclejdk8
    - r: release
      jdk: oraclejdk9
    - r: devel
      jdk: openjdk6
    - r: devel
      jdk: openjdk7
    - r: devel
      jdk: openjdk8
    - r: devel
      jdk: openjdk9
    - r: devel
      jdk: oraclejdk6
    - r: devel
      jdk: oraclejdk7
    - r: devel
      jdk: oraclejdk8
    - r: devel
      jdk: oraclejdk9
    - r: oldrel
      jdk: openjdk8
  
script:
  - |
    java -version
    R CMD build --compact-vignettes=both --md5 .
    export FULL_TEST_SUITE=1
    R CMD check XLConnect*tar.gz
    travis_wait 30 Rscript -e 'covr::codecov()'
