language: r
cache: packages

before_install:
  - echo oracle-java11-installer shared/accepted-oracle-licence-v1-2 boolean true | sudo /usr/bin/debconf-set-selections
  # -echo oracle-java11-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections
  
r_packages:
  - covr
  
r_github_packages:
  - miraisolutions/xlconnectjars
  
matrix:
  include:
    - r: release
      dist: trusty
      addons:
        apt:
          sources:
            - sourceline: 'ppa:webupd8team/java'
          packages:
            - oracle-java8-installer # note that java9 is not available through webupd8team ppa anymore
            - oracle-java8-set-default
    - r: release
      dist: xenial # https://docs.travis-ci.com/user/reference/xenial/
      addons:
        apt:
          sources:
            - sourceline: 'ppa:linuxuprising/java' # note that java10 is not available through this anymore
          packages:
            - oracle-java11-installer
            - oracle-java11-set-default
    - r: devel
      dist: trusty
      addons:
        apt:
          sources:
            - sourceline: 'ppa:webupd8team/java'
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
    - r: devel
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:linuxuprising/java'
          packages:
            - oracle-java11-installer
            - oracle-java11-set-default
    - r: oldrel
      dist: trusty
      addons:
        apt:
          sources:
            - sourceline: 'ppa:webupd8team/java'
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
    - r: oldrel
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:linuxuprising/java'
          packages:
            - oracle-java11-installer
            - oracle-java11-set-default
  
script:
  - |
    java -version
    R CMD build --compact-vignettes=both --md5 .
    export FULL_TEST_SUITE=1
    R CMD check XLConnect*tar.gz
    travis_wait 30 Rscript -e 'covr::codecov()'
